config/routes.rb
Webtopia::Application.routes.draw do

  resources :lists

  resources :blogs

  resources :website_settings

  resources :users
  resources :contents
  resources :pages

  resource :session





#default route redirects to default page set in website config
  root :to => "pages#home_page"

#Feeds etc. pages
  get "sitemap.xml" => "pages#sitemap_page"
  get "rss.xml" => "pages#rss_page"

#Registration and login
  get "register_new_user" => "users#new"
  get "/login" => "pages#login_page"
  post "/login" => "sessions#create"
  get "/logout" => "sessions#destroy"

#Admin Page
  get "admin" => "pages#get_admin"

#find blog
  get "/blog/:id/:name" => "pages#get_blog"

#dynamic page routing routes
  get "/:page_name" => "pages#section_sub_page"
  get "/:section1/:page_name" => "pages#section_sub_page"
  get "/:section1/:section2/:page_name" => "pages#section_sub_page"
  get "/:section1/:section2/:section3/:page_name" => "pages#section_sub_page"
  get "/:section1/:section2/:section3/:section4/:page_name" => "pages#section_sub_page"


end

app/models/list.rb
class List < ActiveRecord::Base
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController

  before_filter :authenticate_admin
  
  # GET /lists
  # GET /lists.json
  def index
    @lists = List.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @lists }
    end
  end

  # GET /lists/1
  # GET /lists/1.json
  def show
    @list = List.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @list }
    end
  end

  # GET /lists/new
  # GET /lists/new.json
  def new
    @list = List.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @list }
    end
  end

  # GET /lists/1/edit
  def edit
    @list = List.find(params[:id])
  end

  # POST /lists
  # POST /lists.json
  def create
    @list = List.new(params[:list])

    respond_to do |format|
      if @list.save
        format.html { redirect_to @list, notice: 'List was successfully created.' }
        format.json { render json: @list, status: :created, location: @list }
      else
        format.html { render action: "new" }
        format.json { render json: @list.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /lists/1
  # PUT /lists/1.json
  def update
    @list = List.find(params[:id])

    respond_to do |format|
      if @list.update_attributes(params[:list])
        format.html { redirect_to @list, notice: 'List was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @list.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /lists/1
  # DELETE /lists/1.json
  def destroy
    @list = List.find(params[:id])
    @list.destroy

    respond_to do |format|
      format.html { redirect_to lists_url }
      format.json { head :ok }
    end
  end
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/views/lists/_form.html.erb
<%= form_for(@list) do |f| %>
  <% if @list.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@list.errors.count, "error") %> prohibited this list from being saved:</h2>

      <ul>
      <% @list.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :url %><br />
    <%= f.text_field :url %>
  </div>
  <div class="field">
    <%= f.label :list_name %><br />
    <%= f.text_field :list_name %>
  </div>
  <div class="field">
    <%= f.label :topic_1 %><br />
    <%= f.text_field :topic_1 %>
  </div>
  <div class="field">
    <%= f.label :topic_2 %><br />
    <%= f.text_field :topic_2 %>
  </div>
  <div class="field">
    <%= f.label :topic_3 %><br />
    <%= f.text_field :topic_3 %>
  </div>
  <div class="field">
    <%= f.label :topic_4 %><br />
    <%= f.text_field :topic_4 %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/lists/edit.html.erb
<h1>Editing list</h1>

<%= render 'form' %>

<%= link_to 'Show', @list %> |
<%= link_to 'Back', lists_path %>

app/views/lists/index.html.erb
<h1>Listing lists</h1>

<table width="600" cellspacing="0" cellpadding="0" border="1">
  <tr>
    <th>Title</th>
    <th>Url</th>
    <th>List Name</th>
    <th>Topic 1</th>
    <th>Topic 2</th>
    <th>Topic 3</th>
    <th>Topic 4</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @lists.each do |list| %>
  <tr>
    <td><%= list.title %></td>
    <td><%= list.url %></td>
    <td><%= list.list_name %></td>
    <td><%= list.topic_1 %></td>
    <td><%= list.topic_2 %></td>
    <td><%= list.topic_3 %></td>
    <td><%= list.topic_4 %></td>
    <td><%= link_to 'Show', list %></td>
    <td><%= link_to 'Edit', edit_list_path(list) %></td>
    <td><%= link_to 'Destroy', list, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New List', new_list_path %>

app/views/lists/new.html.erb
<h1>New list</h1>

<%= render 'form' %>

<%= link_to 'Back', lists_path %>

app/views/lists/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Title:</b>
  <%= @list.title %>
</p>

<p>
  <b>Url:</b>
  <%= @list.url %>
</p>

<p>
  <b>List Name:</b>
  <%= @list.list_name %>
</p>

<p>
  <b>Topic 1:</b>
  <%= @list.topic_1 %>
</p>

<p>
  <b>Topic 2:</b>
  <%= @list.topic_2 %>
</p>

<p>
  <b>Topic 3:</b>
  <%= @list.topic_3 %>
</p>

<p>
  <b>Topic 4:</b>
  <%= @list.topic_4 %>
</p>


<%= link_to 'Edit', edit_list_path(@list) %> |
<%= link_to 'Back', lists_path %>