config/routes.rb
Webtopia::Application.routes.draw do

  resources :lists

  resources :blogs

  resources :website_settings

  resources :users
  resources :contents
  resources :pages

  resource :session





#default route redirects to default page set in website config
  root :to => "pages#home_page"

#Feeds etc. pages
  get "sitemap.xml" => "pages#sitemap_page"
  get "rss.xml" => "pages#rss_page"

#Registration and login
  get "register_new_user" => "users#new"
  get "/login" => "pages#login_page"
  post "/login" => "sessions#create"
  get "/logout" => "sessions#destroy"

#Admin Page
  get "admin" => "pages#get_admin"

#find blog
  get "/blog/:id/:name" => "pages#get_blog"

#dynamic page routing routes
  get "/:page_name" => "pages#section_sub_page"
  get "/:section1/:page_name" => "pages#section_sub_page"
  get "/:section1/:section2/:page_name" => "pages#section_sub_page"
  get "/:section1/:section2/:section3/:page_name" => "pages#section_sub_page"
  get "/:section1/:section2/:section3/:section4/:page_name" => "pages#section_sub_page"


end

app/models/content.rb
class Content < ActiveRecord::Base
end

app/controllers/contents_controller.rb
class ContentsController < ApplicationController

  before_filter :authenticate_admin

#  attr_accessible :content_type, :description, :content

  # GET /contents
  # GET /contents.json
  def index
    @contents = Content.all

    respond_to do |format|
      format.html {render :layout => "layout_1"}
      format.json { render json: @contents }
    end
  end

  # GET /contents/1
  # GET /contents/1.json
  def show
    @content = Content.find(params[:id])

    respond_to do |format|
      format.html {render :layout => "layout_1"}
      format.json { render json: @content }
    end
  end

  # GET /contents/new
  # GET /contents/new.json
  def new
    @content = Content.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @content }
    end
  end

  # GET /contents/1/edit
  def edit
    @content = Content.find(params[:id])
  end

  # POST /contents
  # POST /contents.json
  def create
    @content = Content.new(params[:content])

    @content.user_id = session[:user_id]

    respond_to do |format|
      if @content.save
        format.html { redirect_to @content, notice: 'Content was successfully created.' }
        format.json { render json: @content, status: :created, location: @content }
      else
        format.html { render action: "new" }
        format.json { render json: @content.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /contents/1
  # PUT /contents/1.json
  def update
    @content = Content.find(params[:id])

    @content.user_id = session[:user_id]

    respond_to do |format|
      if @content.update_attributes(params[:content])
        format.html { redirect_to @content, notice: 'Content was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @content.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /contents/1
  # DELETE /contents/1.json
  def destroy
    @content = Content.find(params[:id])
    @content.destroy

    respond_to do |format|
      format.html { redirect_to contents_url }
      format.json { head :ok }
    end
  end
end

app/helpers/contents_helper.rb
module ContentsHelper
end

app/views/contents/_form.html.erb
<%= form_for(@content) do |f| %>
  <% if @content.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@content.errors.count, "error") %> prohibited this content from being saved:</h2>

      <ul>
      <% @content.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

<br/><br/>


<div class="field">
    <%= f.label :content_type %><br />
    <%= f.text_field :content_type %>
</div>


  <div class="field">
    <%= f.label :subject %><br />
    <%= f.text_field :subject %>
  </div>

  <div class="field">
    <%= f.label :topics %><br />
    <%= f.text_field :topics %>
  </div>

  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_field :description %>
  </div>

  <div class="field">
    <%= f.label :content %><br />
    <%= f.text_area :content, :size => "60x30" %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/contents/edit.html.erb
<h1>Editing content</h1>

<%= render 'form' %>

<%= link_to 'Show', @content %> |
<%= link_to 'Back', contents_path %>

app/views/contents/index.html.erb
<h1>Listing contents</h1>



<table width="600" cellspacing="0" cellpadding="0" border="1">
  <tr>
    <th>ID</th>
    <th>Type</th>
    <th>Description</th>
    <th></th>
  </tr>

<% @contents.each do |content| %>
  <tr>
    <td class="table_space"><%= content.id %></td>
    <td class="table_space"><%= content.content_type %></td>
    <td class="table_space"><%= content.description %></td>
    <td class="table_space"><%= link_to 'Show', content %> | <%= link_to 'Edit', edit_content_path(content) %> | <%= link_to 'Delete', content, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Content', new_content_path %>

app/views/contents/new.html.erb
<h1>New content</h1>

<%= render 'form' %>

<%= link_to 'Back', contents_path %>

app/views/contents/show.html.erb
<p id="notice"><%= notice %></p>

<br/><br/>
  <h1>Content:</h1>
<br/><br/>Subject (ID) :  ( <%= @content.id %> ) <%= @content.subject %><br/>
 	Author ID: <%= @content.user_id %> <br/>
	Topics: <%= @content.topics %><br/>
	Popularity: <%= @content.popularity %><br/>
	Content Type: <%= @content.content_type %><br/>
	Description: <%= @content.description %><br/><br/>

<%= link_to 'Edit', edit_content_path(@content) %> | <%= link_to 'Back', contents_path %><br/><br/>

  <textarea cols="60" rows="30"><%= @content.content %></textarea>