config/routes.rb
Webtopia::Application.routes.draw do

  resources :lists

  resources :blogs

  resources :website_settings

  resources :users
  resources :contents
  resources :pages

  resource :session





#default route redirects to default page set in website config
  root :to => "pages#home_page"

#Feeds etc. pages
  get "sitemap.xml" => "pages#sitemap_page"
  get "rss.xml" => "pages#rss_page"

#Registration and login
  get "register_new_user" => "users#new"
  get "/login" => "pages#login_page"
  post "/login" => "sessions#create"
  get "/logout" => "sessions#destroy"

#Admin Page
  get "admin" => "pages#get_admin"

#find blog
  get "/blog/:id/:name" => "pages#get_blog"

#dynamic page routing routes
  get "/:page_name" => "pages#section_sub_page"
  get "/:section1/:page_name" => "pages#section_sub_page"
  get "/:section1/:section2/:page_name" => "pages#section_sub_page"
  get "/:section1/:section2/:section3/:page_name" => "pages#section_sub_page"
  get "/:section1/:section2/:section3/:section4/:page_name" => "pages#section_sub_page"


end

app/models/website_setting.rb
class WebsiteSetting < ActiveRecord::Base
end

app/controllers/website_settings_controller.rb
class WebsiteSettingsController < ApplicationController

  before_filter :authenticate_admin
  before_filter :check_session

    # GET /website_settings
  # GET /website_settings.json
  def index
    @website_settings = WebsiteSetting.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @website_settings }
    end
  end

  # GET /website_settings/1
  # GET /website_settings/1.json
  def show
    @website_setting = WebsiteSetting.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @website_setting }
    end
  end

  # GET /website_settings/new
  # GET /website_settings/new.json
  def new
    @website_setting = WebsiteSetting.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @website_setting }
    end
  end

  # GET /website_settings/1/edit
  def edit
    @website_setting = WebsiteSetting.find(params[:id])
  end

  # POST /website_settings
  # POST /website_settings.json
  def create
    @website_setting = WebsiteSetting.new(params[:website_setting])

    respond_to do |format|
      if @website_setting.save
        format.html { redirect_to @website_setting, notice: 'Website setting was successfully created.' }
        format.json { render json: @website_setting, status: :created, location: @website_setting }
      else
        format.html { render action: "new" }
        format.json { render json: @website_setting.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /website_settings/1
  # PUT /website_settings/1.json
  def update
    @website_setting = WebsiteSetting.find(params[:id])

    respond_to do |format|
      if @website_setting.update_attributes(params[:website_setting])
        format.html { redirect_to @website_setting, notice: 'Website setting was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @website_setting.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /website_settings/1
  # DELETE /website_settings/1.json
  def destroy
    @website_setting = WebsiteSetting.find(params[:id])
    @website_setting.destroy

    respond_to do |format|
      format.html { redirect_to website_settings_url }
      format.json { head :ok }
    end
  end
end

app/helpers/website_settings_helper.rb
module WebsiteSettingsHelper
end

app/views/website_settings/_form.html.erb
<%= form_for(@website_setting) do |f| %>
  <% if @website_setting.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@website_setting.errors.count, "error") %> prohibited this website_setting from being saved:</h2>

      <ul>
      <% @website_setting.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :session_time_out %><br />
    <%= f.number_field :session_time_out %>
  </div>
  <div class="field">
    <%= f.label :home_page %><br />
    <%= f.number_field :home_page %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/website_settings/edit.html.erb
<h1>Editing website_setting</h1>

<%= render 'form' %>

<%= link_to 'Show', @website_setting %> |
<%= link_to 'Back', website_settings_path %>

app/views/website_settings/index.html.erb
<h1>Listing website_settings</h1>

<table>
  <tr>
    <th>Session time out</th>
    <th>Home Page</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @website_settings.each do |website_setting| %>
  <tr>
    <td><%= website_setting.session_time_out %></td>
    <td><%= website_setting.home_page %></td>
    <td><%= link_to 'Show', website_setting %></td>
    <td><%= link_to 'Edit', edit_website_setting_path(website_setting) %></td>
    <td><%= link_to 'Destroy', website_setting, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Website setting', new_website_setting_path %>

app/views/website_settings/new.html.erb
<h1>New website_setting</h1>

<%= render 'form' %>

<%= link_to 'Back', website_settings_path %>

app/views/website_settings/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Session time out:</b>
  <%= @website_setting.session_time_out %>
</p>


<%= link_to 'Edit', edit_website_setting_path(@website_setting) %> |
<%= link_to 'Back', website_settings_path %>